routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::group(['middleware' => 'auth'], function() {

    Route::GET('/', function () {
        return Redirect::route('wallet.index');
    });

    Route::resource('wallet','WalletController',[
        'only' => ['show','index']
    ]);

    Route::resource('users','UsersController');
    Route::resource('faq','FaqController');
    Route::resource('accounts','AccountsController');
    Route::resource('bankacc','BankAccountsController');
    Route::resource('drafts','DraftsController');
    Route::resource('deposits','DepositsController');
});

app/Models/Account.php
<?php

namespace App\Models;

class Account extends \App\Models\Base\Account
{
	protected $fillable = [
		'titre',
		'income_tax',
		'balance_atual'
	];
}

app/Models/BankAccount.php
<?php

namespace App\Models;

class BankAccount extends \App\Models\Base\BankAccount
{
	protected $fillable = [
		'bank_account_titre',
		'agency',
		'account_type',
		'bank_name',
		'account_number'
	];
}

app/Models/Base/Faq.php
<?php

/**
 * Created by Reliese Model.
 * Date: Thu, 10 Oct 2019 19:11:47 -0300.
 */

namespace App\Models\Base;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Faq
 * 
 * @property int $faq_id
 * @property string $question
 * @property string $answer
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 *
 * @package App\Models\Base
 */
class Faq extends Eloquent
{
	protected $primaryKey = 'faq_id';
}

app/Models/Base/Role.php
<?php

/**
 * Created by Reliese Model.
 * Date: Tue, 30 Jul 2019 00:32:32 +0000.
 */

namespace App\Models\Base;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Role
 * 
 * @property int $role_id
 * @property string $role_name
 * @property string $role_informative
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * 
 * @property \Illuminate\Database\Eloquent\Collection $permissions
 * @property \Illuminate\Database\Eloquent\Collection $users
 *
 * @package App\Models\Base
 */
class Role extends Eloquent
{
	protected $primaryKey = 'role_id';

	public function permissions()
	{
		return $this->belongsToMany(\App\Models\Permission::class, 'permission_roles', 'role', 'permission')
					->withPivot('permission_role_id');
	}

	public function users()
	{
		return $this->belongsToMany(\App\Models\User::class, 'role_users', 'role', 'user')
					->withPivot('role_user_id')
					->withTimestamps();
	}
}

app/Models/Base/User.php
<?php

/**
 * Created by Reliese Model.
 * Date: Mon, 05 Aug 2019 14:18:47 -0300.
 */

namespace App\Models\Base;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * Class User
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $cpf
 * @property string $rg
 * @property Carbon $email_verified_at
 * @property string $password
 * @property string $api_token
 * @property string $remember_token
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property string $deleted_at
 *
 * @property Collection $accounts
 * @property Collection $bank_accounts
 * @property Collection $roles
 *
 * @package App\Models\Base
 */
class User extends Authenticatable {

	use SoftDeletes;

	protected $dates = [
		'email_verified_at'
	];

	public function accounts()
	{
		return $this->hasMany(\App\Models\Account::class, 'titre');
	}

	public function bank_accounts()
	{
		return $this->hasMany(\App\Models\BankAccount::class, 'bank_account_titre');
	}

	public function roles()
	{
		return $this->belongsToMany(\App\Models\Role::class, 'role_users', 'user', 'role')
					->withPivot('role_user_id')
					->withTimestamps();
	}
}

app/Models/Config.php
<?php

namespace App\Models;

class Config extends \App\Models\Base\Config
{
	protected $fillable = [
		'irrigation_straight',
		'plant',
		'humidity',
		'config_informative'
	];
}

app/Models/ControlPanel.php
<?php

namespace App\Models;

class ControlPanel extends \App\Models\Base\ControlPanel
{
	protected $fillable = [
		'owner'
	];
}

app/Models/Deposit.php
<?php

namespace App\Models;

class Deposit extends \App\Models\Base\Deposit
{
	protected $fillable = [
		'deposit_value',
		'account',
		'deposit_informative'
	];
}

app/Models/Draft.php
<?php

namespace App\Models;

class Draft extends \App\Models\Base\Draft
{
	protected $fillable = [
		'draft_value',
		'account',
		'bank_account',
		'draft_informative'
	];
}

app/Models/Faq.php
<?php

namespace App\Models;

class Faq extends \App\Models\Base\Faq
{
	protected $fillable = [
		'question',
		'answer'
	];
}

app/Models/Income.php
<?php

namespace App\Models;

class Income extends \App\Models\Base\Income
{
	protected $fillable = [
		'income_value',
		'account',
		'income_informative'
	];
}

app/Models/PasswordReset.php
<?php

namespace App\Models;

class PasswordReset extends \App\Models\Base\PasswordReset
{
	protected $hidden = [
		'token'
	];

	protected $fillable = [
		'email',
		'token'
	];
}

app/Models/Permission.php
<?php

namespace App\Models;

class Permission extends \App\Models\Base\Permission
{
	protected $fillable = [
		'permission_name',
		'permission_informative'
	];
}

app/Models/PermissionRole.php
<?php

namespace App\Models;

class PermissionRole extends \App\Models\Base\PermissionRole
{
	protected $fillable = [
		'permission',
		'role'
	];
}

app/Models/Plant.php
<?php

namespace App\Models;

class Plant extends \App\Models\Base\Plant
{
	protected $fillable = [
		'plant_name',
		'plant_panel_plant_panel'
	];
}

app/Models/Role.php
<?php

namespace App\Models;

class Role extends \App\Models\Base\Role
{
	protected $fillable = [
		'role_name',
		'role_informative'
	];
}

app/Models/RoleUser.php
<?php

namespace App\Models;

class RoleUser extends \App\Models\Base\RoleUser
{
	protected $fillable = [
		'role',
		'user'
	];
}

app/Models/Status.php
<?php

namespace App\Models;

class Status extends \App\Models\Base\Status{
	protected $fillable = [
		'plant',
		'moisture'
	];
}

app/Models/User.php
<?php

namespace App\Models;

class User extends Base\User {

    protected $hidden = [
        'password',
        'remember_token'
    ];

    protected $fillable = [
        'name',
        'email',
        'email_verified_at',
        'password',
        'remember_token'
    ];

    public function hasPermission(Permission $permission){
        return $this->hasAnyRoles($permission->roles);
    }

    public function hasAnyRoles($roles){
        if(is_array($roles) || is_object($roles)){
            return !! $roles->intersect($this->roles)->count();
        }
        return $this->roles->contains('role_name',$roles);
    }
}

app/Models/UserAdress.php
<?php

namespace App\Models;

class UserAdress extends \App\Models\Base\UserAdress
{
	protected $fillable = [
		'user_id',
		'zip_code',
		'city'
	];
}

resources/views/layouts/Inspina/footer.blade.php
<footer class="footer">
    <div class="pull-right">
        Developed By <strong>Akheem CK.</strong>
    </div>
    <div>
        <strong>Kaizen &copy;</strong>  2019-{{date('Y')}}
    </div>
</footer>

resources/views/layouts/Inspina/inspina.blade.php
<!DOCTYPE html>
<html lang='pt br'>
<head>
    <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <meta name='msapplication-tap-highlight' content='no'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>

    <base content='{{url('/')}}'  id='base' target='_self'/> {{--BASE URL FOR AJAX REQUESTS--}}
    <meta name='csrf-token' content='{{csrf_token()}}' /> {{--CSRF Token--}}

    <meta name='description' content='' />
    <meta name='keywords' content='' />
    <title>Kaizen KZN | 0.1v </title>

    <link rel='stylesheet' type='text/css' href='{{asset('css/cores/bootstrap.min.css')}}' />
    <link rel='stylesheet' type='text/css' href='{{asset('css/cores/sweetalert2.min.css')}}' />
    <link rel='stylesheet' type='text/css' href='{{asset('css/cores/inspina.min.css')}}' />
    <link rel='stylesheet' type='text/css' href='{{asset('css/plugins/DataTables/datatables.min.css')}}' />
{{--    <link rel='stylesheet' type='text/css' href='{{asset('css/cores/customInspina.min.css')}}' />--}}
    <link rel='stylesheet' type='text/css' href='{{asset('sources/css/cores/customInspina.css')}}' />
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.8.2/css/all.css' integrity='sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay' crossorigin='anonymous'>
</head>
<body>
{{--WRAPPER--}}
<div id='wrapper'>
    <div class="se-pre-con"></div>

    {{--NAVIGATION--}}
    @include('layouts.Inspina.navigation') {{--END NAVIGATION--}}

    {{--PAGE WRAPER--}}
    <div id='page-wrapper' class='gray-bg'>

        {{--PAGE WRAPPER--}}
        @include('layouts.Inspina.topnavbar') {{--END PAGE WRAPPER--}}

        {{--FOOTER--}}
        @include('layouts.Inspina.footer') {{--END FOOTER--}}


        <div class='row'>
            <div class='panel panel-default'>
                <div class='panel-body'>
                    <div class='panel panel-primary'>
                        @yield('content')
                    </div>
                </div>
            </div>
        </div>

    </div>{{--END PAGE WRAPPER--}}
</div>{{--END WRAPPER--}}

<script type='text/javascript' src='{{asset('js/cores/jquery-3.4.1.min.js')}}'></script> {{--JQUERY CORE--}}
<script type='text/javascript' src='{{asset('js/cores/bootstrap.min.js')}}'></script> {{--BOOTSTRAP CORE--}}
<script type='text/javascript' src='{{asset('js/cores/sweetalert2.min.js')}}'></script> {{--SWEET ALERT--}}
<script type='text/javascript' src='{{asset('js/cores/inspina.min.js')}}'></script> {{--TEMPLATE CORE--}}

<script type='text/javascript' src='{{asset('js/plugins/chartJs/Chart.min.js')}}' defer></script> {{--CHART CORE--}}
<script type='text/javascript' src='{{asset('js/plugins/DataTables/datatables.min.js')}}' defer></script> {{--DATA TABLES--}}
<script type='text/javascript' src='{{asset('js/plugins/bootstrapValidator.min.js')}}' defer></script> {{--INPUT VALIDATOR--}}
<script type='text/javascript' src='{{asset('js/plugins/maskedinput.min.js')}}' defer></script> {{--INPUT MASK--}}
<script type='text/javascript' src='{{asset('js/plugins/jquerydateformat/JqueryDateFormat.min.js')}}' defer></script> {{--JQUERY DATE FORMAT--}}
{{--<script type='text/javascript' src='{{asset('js/cores/customInspina.min.js')}}' defer></script>--}}
<script type='text/javascript' src='{{asset('sources/js/cores/customInspina.js')}}' defer></script>

</body>
</html>

resources/views/layouts/Inspina/navigation.blade.php
<nav class='navbar-default navbar-static-side' role='navigation'>
    <div class='sidebar-collapse'>
        <ul class='nav metismenu' id='side-menu'>
            <li class='nav-header'>

                {{--<div class="dropdown profile-element">
                    <img alt="image" class="rounded-circle" src="img/profile_small.jpg">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="block m-t-xs font-bold">David Williams</span>
                        <span class="text-muted text-xs block">Art Director <b class="caret"></b></span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a class="dropdown-item" href="profile.html">Profile</a></li>
                        <li><a class="dropdown-item" href="contacts.html">Contacts</a></li>
                        <li><a class="dropdown-item" href="mailbox.html">Mailbox</a></li>
                        <li class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="login.html">Logout</a></li>
                    </ul>
                </div>--}}

                <div class='dropdown profile-element'>
                        <span class='clear'>
                            <span class='block m-t-xs'>
                                <strong class='font-bold text-white'>{{current(str_word_count(Auth::user()->name, 1))}}</strong>
                            </span>
                        </span>
                    <p>{{ucfirst(strtolower((empty(Auth::user()->roles->first()->role_name)) ? '' : Auth::user()->roles->first()->role_informative))}}</p>
                    <ul class='dropdown-menu animated fadeInRight m-t-xs'>
                        <li>
                            <i class='fas fa-sign-out-alt fa-2x'></i> Sair
                        </li>
                    </ul>
                </div>
                <div class='logo-element'>
                    <i class="fas fa-hand-holding-usd"></i>
                </div>
            </li>

            @can('admin')
                @can('users_index')
                    <li data-toggle="tooltip" title="PAINEL USUÁRIOS">
                        <a href='{{route('users.index')}}'><i class='fas fa-users fa-2x'></i> <span class='nav-label text-uppercase'>USUÁRIOS</span></a>
                    </li>
                @endcan

                @can('accounts_index')
                    <li data-toggle="tooltip" title="PAINEL CARTEIRAS">
                        <a href='{{route('accounts.index')}}'><i class='fas fa-wallet fa-2x'></i> <span class='nav-label text-uppercase'>CARTEIRAS</span></a>
                    </li>
                @endcan
            @endcan

            @cannot('admin')
                @can('users_show')
                    <li data-toggle="tooltip" title="MEU PAINEL">
                        <a href='{{route('users.show', Auth::id())}}'><i class='fas fa-users fa-2x'></i> <span class='nav-label text-uppercase'>MEUS DADOS</span></a>
                    </li>
                @endcan
                @can('accounts_index')
                    <li data-toggle="tooltip" title="MINHA CARTEIRA">
                        <a href='{{route('wallet.index')}}'><i class='fas fa-wallet fa-2x'></i> <span class='nav-label text-uppercase'>MINHA CARTEIRA</span></a>
                    </li>
                @endcan
            @endcan

            @can('bankacc_index')
                <li data-toggle="tooltip" title="PAINEL CONTAS">
                    <a href='{{route('bankacc.index')}}'><i class='fas fa-university fa-2x'></i> <span class='nav-label text-uppercase'>CONTAS BANCÁRIAS</span></a>
                </li>
            @endcan

            {{--<li class="landing_link">
                <a target="_blank" href="">
                    <i class="fa fa-database"></i>
                    <span class="nav-label">Landing Page</span>
                    <span class="label label-warning pull-right">NEW</span>
                </a>
            </li>--}}

            <li class="special_link">
                <a href="{{route('faq.index')}}" data-toggle="tooltip" title="PERGUNTAS FREQUENTES">
                    <i class="fas fa-question-circle fa-2x"></i>
                    <span class="nav-label">FAQ</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

resources/views/layouts/Inspina/topnavbar.blade.php
<div class='row border-bottom'>
    <nav class='navbar navbar-static-top white-bg' role='navigation'>
        <div class='navbar-header'>
            <a class='navbar-minimalize minimalize-styl-2 btn btn-primary ' href='javascript:void(0)'><i class='fa fa-bars'></i></a>
        </div>
        <ul class='nav navbar-top-links navbar-right text-right'>
            @can('admin')
                <li>
                    <a href='{{route('log-viewer::dashboard')}}' target="_blank">
                        <i class="fas fa-file-code fa-2x"></i>
                    </a>
                </li>
            @endcan
            <li>
                <a href='{{route('users.edit', Auth::id())}}'>
                    <i class="fas fa-user-edit fa-2x"></i>
                </a>
            </li>
            <li>
                <a href='javascript:void(0)' id='logoff'>
                    <i class='fas fa-sign-out-alt fa-2x'></i>
                </a>
            </li>
        </ul>
    </nav>
</div>

resources/views/layouts/app.blade.php
{{--<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>--}}
    <!DOCTYPE html>
<html lang="pt br">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>LaraCoins | 0.1v</title>

    <link rel='stylesheet' type='text/css' href='{{asset('css/cores/bootstrap.min.css')}}' />
    <link rel='stylesheet' type='text/css' href='{{asset('css/cores/inspina.min.css')}}' />

</head>
<body class="gray-bg">

@yield('content')

<script type='text/javascript' src='{{asset('js/cores/jquery-3.4.1.min.js')}}'></script>
<script type='text/javascript' src='{{asset('js/cores/bootstrap.min.js')}}'></script>
</body>
</html>