routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::group(['middleware' => 'auth'], function() {

    Route::GET('/', function () {
        return Redirect::route('wallet.index');
    });

    Route::resource('wallet','WalletController',[
        'only' => ['show','index']
    ]);

    Route::resource('users','UsersController');
    Route::resource('faq','FaqController');
    Route::resource('accounts','AccountsController');
    Route::resource('bankacc','BankAccountsController');
    Route::resource('drafts','DraftsController');
    Route::resource('deposits','DepositsController');
});

app/Models/BankAccount.php
<?php

namespace App\Models;

class BankAccount extends \App\Models\Base\BankAccount
{
	protected $fillable = [
		'bank_account_titre',
		'agency',
		'account_type',
		'bank_name',
		'account_number'
	];
}

app/Models/Base/BankAccount.php
<?php

/**
 * Created by Reliese Model.
 * Date: Tue, 30 Jul 2019 16:51:49 +0000.
 */

namespace App\Models\Base;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class BankAccount
 * 
 * @property int $bank_account_id
 * @property int $bank_account_titre
 * @property string $agency
 * @property string $account_type
 * @property string $bank_name
 * @property string $account_number
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property string $deleted_at
 * 
 * @property \App\Models\User $user
 *
 * @package App\Models\Base
 */
class BankAccount extends Eloquent
{
	use \Illuminate\Database\Eloquent\SoftDeletes;
	protected $primaryKey = 'bank_account_id';

	protected $casts = [
		'bank_account_titre' => 'int'
	];

	public function user()
	{
		return $this->belongsTo(\App\Models\User::class, 'bank_account_titre');
	}
}

app/Http/Controllers/BankAccountsController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Models\User;
use App\Models\BankAccount;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Auth\Access\AuthorizationException;

class BankAccountsController extends Controller {

    /**
     * Display a listing of the resource.
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function index() {
        $this->authorize('bankacc_index');
        try {
            $bankaccounts = BankAccount::query()->select(['bank_accounts.*','users.name as bank_acc_titre'])
                ->join('users','users.id','bank_accounts.bank_account_titre');

            if (!Gate::allows('investor')) {
                $bankaccounts->where('bank_accounts.bank_account_titre', Auth::id());
            }

            $bankaccounts = $bankaccounts->get();
        }
        catch (Exception $exception) {
            report($exception);
        }
        finally {
            return view('kaizen.bankaccounts.index',compact('bankaccounts'));
        }
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function create() {
        $this->authorize('bankacc_create');
        try {
            $bankaccounts = new BankAccount();
            $bankaccounts->bank_acc_titre = User::all();
        }
        catch (Exception $exception) {
            report($exception);
        }
        finally {
            return view('kaizen.bankaccounts.form',compact('bankaccounts'));
        }
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function store(Request $request){
        $this->authorize('bankacc_store', $request);
        try {
            DB::beginTransaction();
            BankAccount::insert([
                'bank_account_titre' => $request->bank_account_titre,
                'agency' => $request->agency,
                'account_type' => $request->account_type,
                'bank_name' => $request->bank_name,
                'account_number' => $request->account_number,
            ]);
            DB::commit();
        }
        catch (Exception $exception) {
            report($exception);
            DB::rollBack();
        }
        finally {
            return redirect()->route('bankacc.index');
        }
    }

    /**
     * Display the specified resource.
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function show($id) {
        $this->authorize('bankacc_show');
        try {
            $bankaccounts = BankAccount::find($id);
        }
        catch (Exception $exception) {
            report($exception);
        }
        finally {
            return view('kaizen.bankaccounts.show',compact('bankaccounts'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function edit($id){
        $this->authorize('bankacc_edit');
        try {
            $bankaccounts = BankAccount::find($id);
            $bankaccounts->bank_acc_titre = User::all();
        }
        catch (Exception $exception) {
            report($exception);
        }
        finally {
            return view('kaizen.bankaccounts.form',compact('bankaccounts'));
        }
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function update(Request $request, $id){
        $this->authorize('bankacc_update',$request);
        try {
            DB::beginTransaction();
            BankAccount::where('bank_account_id',$id)->update([
                'bank_account_titre' => $request->bank_account_titre,
                'agency' => $request->agency,
                'account_type' => $request->account_type,
                'bank_name' => $request->bank_name,
                'account_number' => $request->account_number,
            ]);
            DB::commit();
        }
        catch (Exception $exception) {
            report($exception);
            DB::rollBack();
        }
        finally {
            return redirect()->route('bankacc.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function destroy($id){
        $this->authorize('bankacc_destroy');
        try {
            BankAccount::destroy($id);
        }
        catch (Exception $exception) {
            report($exception);
        }
        finally {
            return redirect()->route('bankacc.index');
        }
    }
}

resources/views/kaizen/bankaccounts/form.blade.php
@extends('layouts.Inspina.inspina')
@section('content')
    <div class='panel-heading text-center font-bold'>CONTAS BANCÁRIAS</div>
    <div class='panel-body'>
        @if($_SERVER['REQUEST_URI'] === '/bankacc/create' && empty($bankaccounts->bank_account_id))
            <form method='POST' action='{{route('bankacc.store')}}' accept-charset='UTF-8' autocomplete='on' data-toggle='validator'>
                @else
                    <form method='POST' action='{{route('bankacc.update', $bankaccounts->bank_account_id)}}' accept-charset='UTF-8' autocomplete='on' data-toggle='validator'>
                        @method('PATCH') @endif @csrf

                        <div class='form-group row'>
                            <div class='col-sm-12 col-md-12'>
                                <label class='control-label' for='bank_account_titre'>TITULAR</label>
                                <select id='bank_account_titre' name='bank_account_titre' class='form-control' required>
{{--                                    @can('investor')--}}
{{--                                        <option value='{{Auth::id()}}' selected> {{Auth::user()->name}}</option>--}}
{{--                                    @endcan--}}
{{--                                    @cannot('investor')--}}
                                        <option readonly>ESCOLHA UM TITULAR PARA ESTA CONTA BANCÁRIA</option>
                                        @foreach($bankaccounts->bank_acc_titre as $bank_acc_titre)
                                            @if(empty($bankaccounts->bank_acc_titre))
                                                <option value='{{$bank_acc_titre->id}}'>{{$bank_acc_titre->name}}</option>
                                            @else
                                                <option value='{{$bank_acc_titre->id}}' {{ ($bank_acc_titre->id === $bankaccounts->bank_account_titre) ? 'selected ' : ''}}> {{$bank_acc_titre->name}}</option>
                                            @endif
                                        @endforeach
{{--                                    @endcannot--}}
                                </select>
                            </div>
                        </div>

                        <div class='form-group row'>
                            <div class='col-sm-12 col-md-4'>
                                <label class='control-label' for='agency'>AGÊNCIA</label>
                                <input type='number' class='form-control' name='agency' id='agency' value='{{$bankaccounts->agency}}' data-error='SOMENTE NÚMEROS' required>
                                <div class='help-block with-errors'></div>
                            </div>

                            <div class='col-sm-12 col-md-4'>
                                <label class='control-label' for='account_number'>NÚMERO DA CONTA</label>
                                <input type='number' class='form-control' name='account_number' id='account_number' value='{{$bankaccounts->account_number}}' required>
                            </div>

                            <div class='col-sm-12 col-md-4'>
                                <label for="account_type">TIPO DE CONTA</label>
                                <select name="account_type" id="account_type" class='form-control' required>
                                    <option value="CC">CONTA CORRENTE</option>
                                    <option value="CP">CONTA POUPANÇA</option>
                                </select>
                            </div>
                        </div>

                        <div class='form-group row'>
                            <div class='col-sm-12 col-md-12'>
                                <label class='control-label' for='bank_name'>NOME DO BANCO</label>
                                <input type='text' class='form-control' name='bank_name' id='bank_name' value='{{$bankaccounts->bank_name}}' required>
                            </div>
                        </div>

                        <hr/>

                        <div class='row'>
                            <div class='col-sm-12 col-md-12 text-center'>
                                <button class='btn btn-success btn-block btn-rounded' type='submit' id='submit'>Salvar</button>
                                <button class='btn btn-warning btn-block btn-rounded' type='reset'>Limpar</button>
                            </div>
                        </div>
                    </form>
            </form>
    </div>
@endsection

resources/views/kaizen/bankaccounts/index.blade.php
@extends('layouts.Inspina.inspina')
@section('content')
    <div class='panel-heading text-center'>CONTAS BANCÁRIAS</div>
    <div class='panel-body'>
        @can('bankacc_create',$bankaccounts)
            <div class="row">
                <span class="container">
                    <a class="btn btn-info btn-rounded" href="{{route('bankacc.create')}}"><i class="fas fa-user-plus"></i>   NOVO CONTA BANCÁRIA</a>
                </span>
            </div>
        @endcan
        @can('bankacc_index',$bankaccounts)
            <table class='bs-dataTables table-striped table-bordered table-hover table-condensed'>
                <thead>
                <tr>
                    <th class='font-weight-bold text-center'>INFO</th>
                    <th class='font-weight-bold text-center'>TITULAR</th>
                    <th class='font-weight-bold text-center'>AGÊNCIA</th>
                    <th class='font-weight-bold text-center'>Nº DA CONTA</th>
                    <th class='font-weight-bold text-center'>BANCO</th>
                    <th class='font-weight-bold text-center'>TIPO</th>
                    <th class='font-weight-bold text-center'>AÇÕES</th>
                </tr>
                </thead>
                <tbody>
                @foreach($bankaccounts as $bankaccount)
                    <tr>
                        <td class='text-center'>
                            @can('bankacc_show',$bankaccount)
                                <a href='javascript:void(0)'>
                                    <i class='fas fa-info-circle fa-2x text-info'></i>
                                </a>
                            @endcan
                        </td>
                        <td class='text-center'>{{$bankaccount->bank_acc_titre}}</td>
                        <td class='text-center'>{{$bankaccount->agency}}</td>
                        <td class='text-center'>{{$bankaccount->account_number}}</td>
                        <td class='text-center text-uppercase'>{{$bankaccount->bank_name}}</td>
                        <td class='text-center'>{{$bankaccount->account_type}}</td>
                        <td class='text-center'>
                            @can('bankacc_edit',$bankaccount)
                                <a href='{{route('bankacc.edit',$bankaccount->bank_account_id)}}'>
                                    <i class='fas fa-edit fa-2x text-success'></i>
                                </a>
                            @endcan
                            @can('bankacc_destroy',$bankaccount)
                                <a href='{{route('bankacc.destroy',$bankaccount->bank_account_id)}}'>
                                    <i class='fas fa-trash-alt fa-2x text-danger'></i>
                                </a>
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @endcan
    </div>
@endsection

resources/views/kaizen/bankaccounts/show.blade.php
@extends('layouts.Inspina.inspina')
@section('content')
@endsection