routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::group(['middleware' => 'auth'], function() {

    Route::GET('/', function () {
        return Redirect::route('wallet.index');
    });

    Route::resource('wallet','WalletController',[
        'only' => ['show','index']
    ]);

    Route::resource('users','UsersController');
    Route::resource('faq','FaqController');
    Route::resource('accounts','AccountsController');
    Route::resource('bankacc','BankAccountsController');
    Route::resource('drafts','DraftsController');
    Route::resource('deposits','DepositsController');
});

app/Models/Base/Draft.php
<?php

/**
 * Created by Reliese Model.
 * Date: Tue, 06 Aug 2019 14:50:23 -0300.
 */

namespace App\Models\Base;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Draft
 * 
 * @property int $draft_id
 * @property float $draft_value
 * @property int $account
 * @property int $bank_account
 * @property string $draft_proof
 * @property string $draft_informative
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * 
 *
 * @package App\Models\Base
 */
class Draft extends Eloquent
{
	protected $primaryKey = 'draft_id';

	protected $casts = [
		'draft_value' => 'float',
		'account' => 'int',
		'bank_account' => 'int'
	];

	public function account()
	{
		return $this->belongsTo(\App\Models\Account::class, 'account');
	}

	public function bank_account()
	{
		return $this->belongsTo(\App\Models\BankAccount::class, 'bank_account');
	}
}

app/Models/Draft.php
<?php

namespace App\Models;

class Draft extends \App\Models\Base\Draft
{
	protected $fillable = [
		'draft_value',
		'account',
		'bank_account',
		'draft_informative'
	];
}

app/Http/Controllers/DraftsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Helpers\DepositsHelperController;
use App\Http\Controllers\Helpers\DraftsHelperController;
use App\Models\Account;
use App\Models\Draft;
use App\Models\User;
use Exception;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class DraftsController extends Controller {

    /**
     * DraftsController constructor.
     */
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function index() {
        $this->authorize('drafts_index');
        try {
            $drafts = Draft::all();
        }
        catch (Exception $exception) {
            report($exception);
        }
        finally {
            return view('kaizen.drafts.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function create() {
        $this->authorize('drafts_create');
        try {
            $drafts = new Account();
            $accounts = Account::query()->select(['accounts.*','users.name as titre_name'])
                ->join('users','users.id','accounts.titre')->get();

        } catch (Exception $exception) {
            report($exception);
        }

        finally {
            return view('kaizen.drafts.form',compact('drafts','accounts'));
        }

    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function store(Request $request) {
        $this->authorize('drafts_store');
        try {
            if ($request->hasFile('draft_proof') && $request->file('draft_proof')->isValid()) {

                $titre = User::find(Account::find($request->account)->titre); #ACCOUNT OWNER

                $receipt_name = DepositsHelperController::make_receipt_name("$request->draft_value", $request->draft_proof->extension(), $titre->cpf); #FILE NAME
                $receipt_path = DepositsHelperController::make_receipt_path($titre->rg); #FILEPATH

                Draft::insert([
                    'draft_value' => $request->draft_value,
                    'account' => $request->account,
                    'draft_proof' => (string) $receipt_path.$receipt_name,
                    'draft_informative' => $request->draft_informative,
                ]); #DATA PERSISTENCE

                $upload = $request->draft_proof->storeAs((string) $receipt_path, (string) $receipt_name);

                DB::commit();
            }
        }

        catch (Exception $exception) {
            report($exception);
            DB::rollBack();
            return redirect()->back()->withInput();
        }

        finally {
            return redirect()->route('wallet.index');
        }
    }

    /**
     * Display the specified resource.
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function show($id) {
        $this->authorize('drafts_show');
        try {}
        catch (Exception $exception) {
            report($exception);
        }
        finally {}
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function edit($id) {
        $this->authorize('drafts_edit');
        try {}
        catch (Exception $exception) {
            report($exception);
        }
        finally {}
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function update(Request $request, $id) {
        $this->authorize('drafts_update');
        try {}
        catch (Exception $exception) {
            report($exception);
        }
        finally {}
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function destroy($id) {
        $this->authorize('drafts_destroy');
        try {}
        catch (Exception $exception) {
            report($exception);
        }
        finally {}
    }
}

resources/views/kaizen/drafts/form.blade.php
@extends('layouts.Inspina.inspina')
@section('content')
    <div class='panel-heading text-center'>SAQUES</div>
    <div class='panel-body'>
        @if($_SERVER['REQUEST_URI'] === '/drafts/create' && empty($drafts->id))
            <form method='POST' action='{{route('drafts.store')}}' enctype='multipart/form-data' accept-charset='UTF-8' autocomplete='on' data-toggle='validator'>
                @else
                    <form action='{{route('drafts.update', $drafts->draft_id)}}' accept-charset='UTF-8' autocomplete='on' enctype='multipart/form-data' data-toggle='validator'>
                        @method('PATCH') @endif @csrf

                        <div class='form-group row'>
                            <div class='col-sm-12 col-md-12'>
                                <label class='control-label' for='draft_value'>Valor</label>
                                <input type='number' class='form-control' name='draft_value' id='draft_value' value='{{$drafts->draft_value}}' data-error='Insira um valor válido' required min="100" step="0.01" placeholder="MINIMO R$ 100,00">
                                <div class='help-block with-errors'></div>
                            </div>
                        </div>

                        <div class='form-group row'>
                            <div class='col-sm-12 col-md-12'>
                                <label class='control-label' for='account'>Conta</label>
                                <select name="account" id="account" class='form-control' required data-error='Insira um valor válido'>
                                    @forelse($accounts as $account)
                                        <option value="{{$account->account_id}}">{{$account->titre_name}}</option>
                                    @empty
                                        <option>NÃO FORAM ENCONTRADAS CONTAS</option>
                                    @endforelse
                                </select>
                                <div class='help-block with-errors'></div>
                            </div>
                        </div>

                        <div class='form-group row'>
                            <div class='col-sm-12 col-md-12'>
                                <label for='photo'>Comprovante de pagamento</label>
                                <input type='file' class='form-control-file' id='draft_proof' name='draft_proof' required>
                            </div>
                        </div>

                        <hr/>

                        <div class='row'>
                            <div class='col-sm-12 col-md-12 text-center'>
                                <button class='btn btn-success btn-block btn-rounded' type='submit' id='submit'>Salvar</button>
                                <button class='btn btn-warning btn-block btn-rounded' type='reset'>Limpar</button>
                            </div>
                        </div>
                    </form>
            </form>
    </div>
@endsection

resources/views/kaizen/drafts/index.blade.php
@extends('layouts.Inspina.inspina')
@section('content')
    <div class='panel-heading text-center'>CONTAS BANCÁRIAS</div>
    <div class='panel-body'>
        @can('bankacc_create',$bankaccounts)
            <div class="row">
                <span class="container">
                    <a class="btn btn-info btn-rounded" href="{{route('bankacc.create')}}"><i class="fas fa-user-plus"></i>   NOVO CONTA BANCÁRIA</a>
                </span>
            </div>
        @endcan
        @can('bankacc_index',$bankaccounts)
            <table class='bs-dataTables table-striped table-bordered table-hover table-condensed'>
                <thead>
                <tr>
                    <th class='font-weight-bold text-center'>INFO</th>
                    <th class='font-weight-bold text-center'>TITULAR</th>
                    <th class='font-weight-bold text-center'>AGÊNCIA</th>
                    <th class='font-weight-bold text-center'>Nº DA CONTA</th>
                    <th class='font-weight-bold text-center'>BANCO</th>
                    <th class='font-weight-bold text-center'>TIPO</th>
                    <th class='font-weight-bold text-center'>AÇÕES</th>
                </tr>
                </thead>
                <tbody>
                @foreach($bankaccounts as $bankaccount)
                    <tr>
                        <td class='text-center'>
                            @can('bankacc_show',$bankaccount)
                                <a href='javascript:void(0)'>
                                    <i class='fas fa-info-circle fa-2x text-info'></i>
                                </a>
                            @endcan
                        </td>
                        <td class='text-center'>{{$bankaccount->bank_acc_titre}}</td>
                        <td class='text-center'>{{$bankaccount->agency}}</td>
                        <td class='text-center'>{{$bankaccount->account_number}}</td>
                        <td class='text-center text-uppercase'>{{$bankaccount->bank_name}}</td>
                        <td class='text-center'>{{$bankaccount->account_type}}</td>
                        <td class='text-center'>
                            @can('bankacc_edit',$bankaccount)
                                <a href='{{route('bankacc.edit',$bankaccount->bank_account_id)}}'>
                                    <i class='fas fa-edit fa-2x text-success'></i>
                                </a>
                            @endcan
                            @can('bankacc_destroy',$bankaccount)
                                <a href='{{route('bankacc.destroy',$bankaccount->bank_account_id)}}'>
                                    <i class='fas fa-trash-alt fa-2x text-danger'></i>
                                </a>
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @endcan
    </div>
@endsection