routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::group(['middleware' => 'auth'], function() {

    Route::GET('/', function () {
        return Redirect::route('wallet.index');
    });

    Route::resource('wallet','WalletController',[
        'only' => ['show','index']
    ]);

    Route::resource('users','UsersController');
    Route::resource('faq','FaqController');
    Route::resource('accounts','AccountsController');
    Route::resource('bankacc','BankAccountsController');
    Route::resource('drafts','DraftsController');
    Route::resource('deposits','DepositsController');
});

app/Models/Base/Deposit.php
<?php

/**
 * Created by Reliese Model.
 * Date: Wed, 09 Oct 2019 13:58:08 -0300.
 */

namespace App\Models\Base;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Deposit
 * 
 * @property int $deposit_id
 * @property float $deposit_value
 * @property int $account
 * @property string $deposit_proof
 * @property string $deposit_informative
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * 
 *
 * @package App\Models\Base
 */
class Deposit extends Eloquent
{
	protected $primaryKey = 'deposit_id';

	protected $casts = [
		'deposit_value' => 'float',
		'account' => 'int'
	];

	public function account()
	{
		return $this->belongsTo(\App\Models\Account::class, 'account');
	}
}

app/Models/Deposit.php
<?php

namespace App\Models;

class Deposit extends \App\Models\Base\Deposit
{
	protected $fillable = [
		'deposit_value',
		'account',
		'deposit_informative'
	];
}

app/Http/Controllers/DepositsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Helpers\DraftsHelperController;
use App\Models\Account;
use App\Models\Deposit;
use App\Models\User;
use Gate;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\services\DepositsService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Auth\Access\AuthorizationException;
use App\Http\Controllers\Helpers\DepositsHelperController;

class DepositsController extends DepositsHelperController {

    /**
     * Display a listing of the resource.
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function index() {
        $this->authorize('deposits_index');
        try {
            if (Gate::allows('investor')) {
                $deposits = DepositsService::show_authenticated();
            }
        }

        catch (Exception $exception) {
            report($exception);
        }

        finally {
            print '<pre>'; print_r($deposits->toArray()); die;
            #return view('kaizen.deposits.index' ,compact('deposits'));
        }
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function create() {
        $this->authorize('deposits_create');
        try {
            $deposits = new Account();
            $accounts = Account::query()
                ->select(['accounts.*','users.name as titre_name'])
                ->join('users','users.id','accounts.titre')->get();

        }
        catch (Exception $exception) {
            report($exception);
        }
        finally {
            return view('kaizen.deposits.form',compact('deposits','accounts'));
        }

    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function store(Request $request) {
        $this->authorize('deposits_store');
        try {
            if ($request->hasFile('deposit_proof') && $request->file('deposit_proof')->isValid()) {

                $titre = User::find(Account::find($request->account)->titre); #ACCOUNT OWNER

                $receipt_name = DraftsHelperController::make_receipt_name("$request->deposit_value", $request->deposit_proof->extension(), $titre->cpf); #FILE NAME
                $receipt_path = DraftsHelperController::make_receipt_path($titre->rg); #FILEPATH

                Deposit::insert([
                    'deposit_value' => $request->deposit_value,
                    'account' => $request->account,
                    'deposit_proof' => (string) $receipt_path.$receipt_name,
                    'deposit_informative' => $request->deposit_informative,
                ]); #DATA PERSISTENCE

                $upload = $request->deposit_proof->storeAs((string) $receipt_path, (string) $receipt_name);

                DB::commit();
            }
        }
        catch (Exception $exception) {
            report($exception);
            DB::rollBack();
            return redirect()->back()->withInput();
        }

        finally {
            return redirect()->route('wallet.index');
        }
    }

    /**
     * Display the specified resource.
     * @param int $id
     * @return Response
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function show($id)
    {
        $this->authorize('deposits_show');
        try {
        } catch (Exception $exception) {
            report($exception);
        } finally {
        }
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function edit($id)
    {
        $this->authorize('deposits_edit');
        try {
        } catch (Exception $exception) {
            report($exception);
        } finally {
        }
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function update(Request $request, $id) {
        $this->authorize('deposits_update');
        try {

        }

        catch (Exception $exception) {
            report($exception);
            DB::rollBack();
            return redirect()->back()->withInput();
        }

        finally {

        }
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     * @author Gilson Vieira Castro Júnior <castrok@live.com (61) 9 9209-6171>
     */
    public function destroy($id)
    {
        $this->authorize('deposits_destroy');
        try {
        } catch (Exception $exception) {
            report($exception);
        } finally {
        }
    }
}

resources/views/kaizen/deposits/form.blade.php
@extends('layouts.Inspina.inspina')
@section('content')
    <div class='panel-heading text-center'>DEPÓSITOS</div>
    <div class='panel-body'>
        @if($_SERVER['REQUEST_URI'] === '/deposits/create' && empty($deposits->id))
            <form method='POST' action='{{route('deposits.store')}}' enctype='multipart/form-data' accept-charset='UTF-8' autocomplete='on' data-toggle='validator'>
                @else
                    <form action='{{route('deposits.update', $deposits->deposit_id)}}' accept-charset='UTF-8' autocomplete='on' enctype='multipart/form-data' data-toggle='validator'>
                        @method('PATCH') @endif @csrf

                        <div class='form-group row'>
                            <div class='col-sm-12 col-md-12'>
                                <label class='control-label' for='deposit_value'>Valor</label>
                                <input type='number' class='form-control' name='deposit_value' id='deposit_value' value='{{$deposits->deposit_value}}' data-error='Insira um valor válido' required min="100" step="0.01" placeholder="MINIMO R$ 100,00">
                                <div class='help-block with-errors'></div>
                            </div>
                        </div>

                        <div class='form-group row'>
                            <div class='col-sm-12 col-md-12'>
                                <label class='control-label' for='account'>Conta</label>
                                <select name="account" id="account" class='form-control' required data-error='Insira um valor válido'>
                                    @forelse($accounts as $account)
                                        <option value="{{$account->account_id}}">{{$account->titre_name}}</option>
                                    @empty
                                        <option>NÃO FORAM ENCONTRADAS CONTAS</option>
                                    @endforelse
                                </select>
                                <div class='help-block with-errors'></div>
                            </div>
                        </div>

                        <div class='form-group row'>
                            <div class='col-sm-12 col-md-12'>
                                <label for='photo'>Comprovante de depósito</label>
                                <input type='file' class='form-control-file' id='deposit_proof' name='deposit_proof' required>
                            </div>
                        </div>

                        <hr/>

                        <div class='row'>
                            <div class='col-sm-12 col-md-12 text-center'>
                                <button class='btn btn-success btn-block btn-rounded' type='submit' id='submit'>Salvar</button>
                                <button class='btn btn-warning btn-block btn-rounded' type='reset'>Limpar</button>
                            </div>
                        </div>
                    </form>
            </form>
    </div>
@endsection

resources/views/kaizen/deposits/index.blade.php
@extends('layouts.Inspina.inspina')
@section('content')
    <div class='panel-heading text-center'>DEPÓSITOS</div>
    <div class='panel-body'>
        @can('deposits_create',$deposits)
            <div class="row">
                <span class="container">
                    <a class="btn btn-info btn-rounded" href="{{route('deposits.create')}}"><i class="fas fa-user-plus"></i>   NOVO DEPÓSITO</a>
                </span>
            </div>
        @endcan
        @can('deposits_index',$deposits)
            <table class='bs-dataTables table-striped table-bordered table-hover table-condensed'>
                <thead>
                <tr>
                    <th class='font-weight-bold text-center'>INFO</th>
                    <th class='font-weight-bold text-center'>TITULAR</th>
                    <th class='font-weight-bold text-center'>VALOR</th>
                    <th class='font-weight-bold text-center'>DATA</th>
                    <th class='font-weight-bold text-center'>AÇÕES</th>
                </tr>
                </thead>
                <tbody>
                @foreach($deposits as $deposit)
                    <tr>
                        <td class='text-center'>
                            @can('deposits_show',$deposit)
                                <a href='javascript:void(0)'>
                                    <i class='fas fa-info-circle fa-2x text-info'></i>
                                </a>
                            @endcan
                        </td>
                        <td class='text-center'>{{$deposit->titre_name}}</td>
                        <td class='text-center'>
                            @can('deposits_edit',$deposit)
                                <a href='{{route('deposits.edit',$deposit->deposit_id)}}'>
                                    <i class='fas fa-edit fa-2x text-success'></i>
                                </a>
                            @endcan
                            @can('deposits_destroy',$deposit)
                                <a href='{{route('deposits.destroy', $deposit->deposit_id)}}'>
                                    <i class='fas fa-trash-alt fa-2x text-danger'></i>
                                </a>
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @endcan
    </div>
@endsection